.. _`EveryBlock`: http://www.everyblock.com/

.. |everyblock-intro| replace::

  `EveryBlock`_ est un site internet qui filtre un assortiment de nouvelles locales par localisation, permettant de garder une trace de ce qui se passe dans son quartier, dans son arrondissement ou dans toute la ville. EveryBlock, dont l'existence est rendue possible grâce à une aide de la Fondation Knight, cherche à répondre à la question "Que se passe-t-il dans mon quartier ?" Un aspect-clé de tout problème lié à des données localisées est une bonne cartographie – et quand EveryBlock a cherché à réaliser cette cartographie, il s'est tourné vers OpenLayers.
